name: us-houses-eda

channels:
  - conda-forge

dependencies:
  - python==3.7.12
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - seaborn
  - plotly
  - geopandas
  - geopy
  - ipykernel 
  - autopep8
  - dash
  - dash-core-components
  - dash-html-components